# Generated by Django 4.2.25 on 2025-11-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_question_slug_alter_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag', verbose_name='Теги'),
        ),
    ]
