"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from configparser import ConfigParser

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

config = ConfigParser()
config.read(os.path.join(BASE_DIR, 'conf', 'local.conf'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get('project', 'SECRET_KEY', fallback='<UNFILLED_SECRET_KEY>')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Что я сам написал
INSTALLED_APPS += [
    'core',
    'testings',
    'centrifuge'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'
CSRF_HEADER_NAME = 'X-CSRFToken'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'seminar_2',      # The name of your PostgreSQL database
        'USER': 'admin',  # The username to connect with
        'PASSWORD': 'admin', # The password for the user
        'HOST': 'localhost',         # The database server hostname or IP
        'PORT': '5432',              # The PostgreSQL port (default is 5432)
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'core.User'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# SESSION_COOKIE_AGE = 1209600  # 2 недели
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Сессия не expires при закрытии браузера

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config.get('redis', 'LOCATION', fallback='redis://localhost:6379/1'),
        'TIMEOUT': config.getint('redis', 'LIFETIME', fallback=9660),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": config.get('redis', 'PREFIX', fallback='seminar') # Optional: add a prefix to all cache keys
    }
}


# Centrifugo

CENTRIFUGE_HOST = config.get('centrifuge', 'HOST', fallback='http://localhost:8035')
CENTRIFUGE_URL = config.get('centrifuge', 'URL', fallback='/centrifuge')
CENTRIFUGE_API_KEY = config.get('centrifuge', 'API_KEY', fallback='')
CENTRIFUGE_SECRET = config.get('centrifuge', 'SECRET', fallback='')
CENTRIFUGE_TOKEN_EXPIRE = config.getint('centrifuge', 'TOKEN_EXPIRE', fallback=120 * 60)
CENTRIFUGE_TIMEOUT = config.getint('centrifuge', 'TIMEOUT', fallback=1)
CENTRIFUGE_ENABLED = config.getboolean('centrifuge', 'ENABLED', fallback=False)

# Mailing

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config.get('smtp', 'HOST', fallback='127.0.0.1')
EMAIL_PORT = config.getint('smtp', 'PORT', fallback=1025)
SENDER_EMAIL = config.get('smtp', 'SENDER_EMAIL')
SERVER_EMAIL = SENDER_EMAIL
UNSUBSCRIBE_TOKEN = config.get('smtp', 'UNSUBSCRIBE_TOKEN', fallback='!SECRET_TOKEN!')
USE_TLS = False
